name: Android

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: print secrets
        run: |
          echo $DEV_ENV_FILE
          echo $DEV_ENV_FILE >> ./src/constants.ts
          cat src/constants
      - uses: actions/checkout@v2
      - name: Use Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: npm ci

      - run: ./gradlew assembleDebug -Dorg.gradle.logging.level=info
        working-directory: android
        name: Build Android apk (debug)
